---
- include: server.yml
  tags: apt-cacher-ng:server
  when: apt_cacher_ng_server and ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
- include: client.yml
  tags: apt-cacher-ng:client
  when: not apt_cacher_ng_server
