---
- name: Update sources.
  apt: update_cache=true cache_valid_time=86400

- name: Install apt-cacher-ng.
  apt:
    name: apt-cacher-ng
    state: present
    update_cache: true

- name: Make sure apt-cacher-ng start at boot.
  service:
    name: apt-cacher-ng
    state: started
    enabled: true

- name: Create CacheDir.
  file:
    path: "{{ apt_cacher_ng_cache_dir }}"
    owner: apt-cacher-ng
    group: apt-cacher-ng
    mode: 02755
    state: directory

- name: Update config.
  lineinfile:
    path: /etc/apt-cacher-ng/acng.conf
    regexp: "{{ item.0 }}"
    line: "{{ item.1 }}"
    backrefs: true
  with_together:
    - ["^# Port:", "^CacheDir:\ "]
    - ["Port: {{ apt_cacher_ng_port }}", "CacheDir: {{ apt_cacher_ng_cache_dir }}"]
  notify:
    - restart apt-cacher-ng
