---
- name: Unhold apt-cacher-ng
  dpkg_selections:
    name: apt-cacher-ng
    selection: install

- name: Install apt-cacher-ng.
  apt:
    name: apt-cacher-ng={{ apt_cacher_ng_version }}
    state: present
    update_cache: true

- name: Hold apt-cacher-ng
  dpkg_selections:
    name: apt-cacher-ng
    selection: hold

- name: Make sure apt-cacher-ng start at boot.
  service:
    name: apt-cacher-ng
    state: started
    enabled: true

- name: Create CacheDir.
  file:
    path: "{{ apt_cacher_ng_cache_dir }}"
    owner: apt-cacher-ng
    group: apt-cacher-ng
    mode: 02755
    state: directory

- name: Update config.
  lineinfile:
    path: /etc/apt-cacher-ng/acng.conf
    regexp: "{{ item.0 }}"
    line: "{{ item.1 }}"
    backrefs: true
  with_together:
    - ["^# Port:", "^CacheDir:\ ", "^# PassThroughPattern:"]
    - ["Port: {{ apt_cacher_ng_port }}", "CacheDir: {{ apt_cacher_ng_cache_dir }}", "PassThroughPattern: .*:443$"]
  notify:
    - restart apt-cacher-ng

- name: Add keys to apt-cacher-ng proxy.
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state | default('present') }}"
    id: "{{ item.id | default(omit) }}"
  with_items: "{{ import_keys }}"

- name: Add repositories to apt-cacher-ng proxy.
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ import_repository }}"

- name: Update sources.
  apt:
    update_cache: true
    cache_valid_time: 86400
